# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 首頁
    url: '#about'
    weight: 10
  - name: 才藝展示
    url: '#talks'
    weight: 20
  - name: 語言及特長
    url: '#skills'
    weight: 30
  - name: 榮譽及獎勵
    url: '#awards'
    weight: 40
  - name: 社會活動
    url: '#posts'
    weight: 50
  - name: 家庭成員
    url: '#family'
    weight: 60
  - name: 聯絡方式
    url: '#contact'
    weight: 90

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
